SELECT MSGID,
       CASE STATE
         WHEN 0 THEN 'READY'
         WHEN 1 THEN 'WAITING'
         WHEN 2 THEN 'PROCESSED'
         WHEN 3 THEN 'EXPIRED'
         ELSE TO_CHAR(STATE)
       END AS STATE_LABEL,
       ENQ_TIME, DELAY, EXPIRATION
FROM CLOB_TO_BLOB_QTAB
ORDER BY ENQ_TIME DESC
FETCH FIRST 10 ROWS ONLY
/
